# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'siebotUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import PyQt5.QtWidgets

import ncm

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Siebot(object):


    def setupUi(self, Siebot):
        super().__init__()
        Siebot.setObjectName("Siebot")
        Siebot.resize(507, 143)
        
        self.inputNcm = QtWidgets.QPushButton(Siebot)
        self.inputNcm.setGeometry(QtCore.QRect(360, 20, 111, 28))
        self.inputNcm.setDefault(False)
        self.inputNcm.setObjectName("inputNcm")
        self.textEdit = QtWidgets.QTextEdit(Siebot)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 281, 31))
        self.textEdit.setToolTip("")
        self.textEdit.setObjectName("textEdit")
        self.aliquotaText = QtWidgets.QLabel(Siebot)
        self.aliquotaText.setGeometry(QtCore.QRect(360, 60, 130, 51))
        self.aliquotaText.setAlignment(QtCore.Qt.AlignCenter)
        self.aliquotaText.setObjectName("aliquotaText")
        self.descricaoText = QtWidgets.QLabel(Siebot)
        self.descricaoText.setGeometry(QtCore.QRect(20, 60, 291, 51))
        self.descricaoText.setAlignment(QtCore.Qt.AlignCenter)
        self.descricaoText.setObjectName("descricaoText")
        self.retranslateUi(Siebot)
        QtCore.QMetaObject.connectSlotsByName(Siebot)



        #Botao de captar o NCM
        self.inputNcm.clicked.connect(self.clickBotao)


    def retranslateUi(self, Siebot):
        _translate = QtCore.QCoreApplication.translate
        Siebot.setWindowTitle(_translate("Siebot", "Siebot - Alíquota de NCM"))
        self.inputNcm.setText(_translate("Siebot", "Verificar Alíquota"))
        self.aliquotaText.setText(_translate("Siebot", "Aliquota IPI"))
        self.descricaoText.setText(_translate("Siebot", "Descrição IPI"))

    def clickBotao(self):

        tabelaNCM = ncm.AliquotaNCM

        textoDescricao = tabelaNCM.descricaoNCM(self.textEdit.toPlainText())
        textoAliquota = tabelaNCM.aliquotaNCM(self.textEdit.toPlainText())


        self.descricaoText.setText("Descrição: " + '\n' +str(textoDescricao))
        #self.aliquotaText.setText(tabelaNCM.aliquotaNCM('0305.42.00'))
        #self.aliquotaText.setText(tabelaNCM.aliquotaNCM2(textoAliquota))
        self.aliquotaText.setText("Alíquota de: "+'\n'+str(textoAliquota)+'%')
        #print(self.aliquotaText.text())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Siebot = QtWidgets.QDialog()
    ui = Ui_Siebot()
    ui.setupUi(Siebot)
    Siebot.show()
    sys.exit(app.exec_())
